<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.CountMessagesRequest</code>
 */
class CountMessagesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     */
    protected $topic = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *           wildcard or exact topic
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

}

