<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.CountMessagesResponse</code>
 */
class CountMessagesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 messages_count = 1 [json_name = "messagesCount"];</code>
     */
    protected $messages_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $messages_count
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 messages_count = 1 [json_name = "messagesCount"];</code>
     * @return int|string
     */
    public function getMessagesCount()
    {
        return $this->messages_count;
    }

    /**
     * Generated from protobuf field <code>int64 messages_count = 1 [json_name = "messagesCount"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessagesCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->messages_count = $var;

        return $this;
    }

}

