<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.PubMessageResponse</code>
 */
class PubMessageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 status = 1 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 no = 2 [json_name = "no"];</code>
     */
    protected $no = 0;
    /**
     * Generated from protobuf field <code>string msg_uuid = 3 [json_name = "msgUuid"];</code>
     */
    protected $msg_uuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $status
     *     @type int|string $no
     *     @type string $msg_uuid
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 status = 1 [json_name = "status"];</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 1 [json_name = "status"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 no = 2 [json_name = "no"];</code>
     * @return int|string
     */
    public function getNo()
    {
        return $this->no;
    }

    /**
     * Generated from protobuf field <code>int64 no = 2 [json_name = "no"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setNo($var)
    {
        GPBUtil::checkInt64($var);
        $this->no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_uuid = 3 [json_name = "msgUuid"];</code>
     * @return string
     */
    public function getMsgUuid()
    {
        return $this->msg_uuid;
    }

    /**
     * Generated from protobuf field <code>string msg_uuid = 3 [json_name = "msgUuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setMsgUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_uuid = $var;

        return $this;
    }

}

