<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.PubMessageResponse</code>
 */
class PubMessageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 messages_received = 1 [json_name = "messagesReceived"];</code>
     */
    protected $messages_received = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $messages_received
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 messages_received = 1 [json_name = "messagesReceived"];</code>
     * @return int|string
     */
    public function getMessagesReceived()
    {
        return $this->messages_received;
    }

    /**
     * Generated from protobuf field <code>int64 messages_received = 1 [json_name = "messagesReceived"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessagesReceived($var)
    {
        GPBUtil::checkInt64($var);
        $this->messages_received = $var;

        return $this;
    }

}

