<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.PubMessageRequest</code>
 */
class PubMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>bytes body = 2 [json_name = "body"];</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>int64 postpone = 3 [json_name = "postpone"];</code>
     */
    protected $postpone = 0;
    /**
     * Generated from protobuf field <code>int64 expiration = 4 [json_name = "expiration"];</code>
     */
    protected $expiration = 0;
    /**
     * Generated from protobuf field <code>map<string, string> variables = 5 [json_name = "variables"];</code>
     */
    private $variables;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *     @type string $body
     *     @type int|string $postpone
     *     @type int|string $expiration
     *     @type array|\Google\Protobuf\Internal\MapField $variables
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes body = 2 [json_name = "body"];</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>bytes body = 2 [json_name = "body"];</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 postpone = 3 [json_name = "postpone"];</code>
     * @return int|string
     */
    public function getPostpone()
    {
        return $this->postpone;
    }

    /**
     * Generated from protobuf field <code>int64 postpone = 3 [json_name = "postpone"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPostpone($var)
    {
        GPBUtil::checkInt64($var);
        $this->postpone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 4 [json_name = "expiration"];</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 4 [json_name = "expiration"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> variables = 5 [json_name = "variables"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getVariables()
    {
        return $this->variables;
    }

    /**
     * Generated from protobuf field <code>map<string, string> variables = 5 [json_name = "variables"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setVariables($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->variables = $arr;

        return $this;
    }

}

