<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.SubMessageRequest</code>
 */
class SubMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>int64 from_timestamp = 2 [json_name = "fromTimestamp"];</code>
     */
    protected $from_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 to_timestamp = 3 [json_name = "toTimestamp"];</code>
     */
    protected $to_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 max_messages = 4 [json_name = "maxMessages"];</code>
     */
    protected $max_messages = 0;
    /**
     * Generated from protobuf field <code>bool continuous = 5 [json_name = "continuous"];</code>
     */
    protected $continuous = false;
    /**
     * Generated from protobuf field <code>string ack_msg_uuid = 6 [json_name = "ackMsgUuid"];</code>
     */
    protected $ack_msg_uuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *           wildcard or exact topic
     *     @type int|string $from_timestamp
     *     @type int|string $to_timestamp
     *     @type int|string $max_messages
     *     @type bool $continuous
     *     @type string $ack_msg_uuid
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 from_timestamp = 2 [json_name = "fromTimestamp"];</code>
     * @return int|string
     */
    public function getFromTimestamp()
    {
        return $this->from_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 from_timestamp = 2 [json_name = "fromTimestamp"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->from_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 to_timestamp = 3 [json_name = "toTimestamp"];</code>
     * @return int|string
     */
    public function getToTimestamp()
    {
        return $this->to_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 to_timestamp = 3 [json_name = "toTimestamp"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setToTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->to_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_messages = 4 [json_name = "maxMessages"];</code>
     * @return int|string
     */
    public function getMaxMessages()
    {
        return $this->max_messages;
    }

    /**
     * Generated from protobuf field <code>int64 max_messages = 4 [json_name = "maxMessages"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxMessages($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_messages = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool continuous = 5 [json_name = "continuous"];</code>
     * @return bool
     */
    public function getContinuous()
    {
        return $this->continuous;
    }

    /**
     * Generated from protobuf field <code>bool continuous = 5 [json_name = "continuous"];</code>
     * @param bool $var
     * @return $this
     */
    public function setContinuous($var)
    {
        GPBUtil::checkBool($var);
        $this->continuous = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ack_msg_uuid = 6 [json_name = "ackMsgUuid"];</code>
     * @return string
     */
    public function getAckMsgUuid()
    {
        return $this->ack_msg_uuid;
    }

    /**
     * Generated from protobuf field <code>string ack_msg_uuid = 6 [json_name = "ackMsgUuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setAckMsgUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->ack_msg_uuid = $var;

        return $this;
    }

}

