<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.SubMessageResponse</code>
 */
class SubMessageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 status = 1 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string msg_uuid = 2 [json_name = "msgUuid"];</code>
     */
    protected $msg_uuid = '';
    /**
     * Generated from protobuf field <code>map<string, string> variables = 3 [json_name = "variables"];</code>
     */
    private $variables;
    /**
     * Generated from protobuf field <code>bool chunk_last = 4 [json_name = "chunkLast"];</code>
     */
    protected $chunk_last = false;
    /**
     * Generated from protobuf field <code>int64 chunk_no = 5 [json_name = "chunkNo"];</code>
     */
    protected $chunk_no = 0;
    /**
     * Generated from protobuf field <code>int64 total_size = 6 [json_name = "totalSize"];</code>
     */
    protected $total_size = 0;
    /**
     * Generated from protobuf field <code>bytes data = 7 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 8 [json_name = "timestamp"];</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>bool end_of_stream = 9 [json_name = "endOfStream"];</code>
     */
    protected $end_of_stream = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $status
     *     @type string $msg_uuid
     *     @type array|\Google\Protobuf\Internal\MapField $variables
     *     @type bool $chunk_last
     *     @type int|string $chunk_no
     *     @type int|string $total_size
     *     @type string $data
     *     @type int|string $timestamp
     *     @type bool $end_of_stream
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 status = 1 [json_name = "status"];</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 1 [json_name = "status"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg_uuid = 2 [json_name = "msgUuid"];</code>
     * @return string
     */
    public function getMsgUuid()
    {
        return $this->msg_uuid;
    }

    /**
     * Generated from protobuf field <code>string msg_uuid = 2 [json_name = "msgUuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setMsgUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> variables = 3 [json_name = "variables"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getVariables()
    {
        return $this->variables;
    }

    /**
     * Generated from protobuf field <code>map<string, string> variables = 3 [json_name = "variables"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setVariables($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->variables = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool chunk_last = 4 [json_name = "chunkLast"];</code>
     * @return bool
     */
    public function getChunkLast()
    {
        return $this->chunk_last;
    }

    /**
     * Generated from protobuf field <code>bool chunk_last = 4 [json_name = "chunkLast"];</code>
     * @param bool $var
     * @return $this
     */
    public function setChunkLast($var)
    {
        GPBUtil::checkBool($var);
        $this->chunk_last = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 chunk_no = 5 [json_name = "chunkNo"];</code>
     * @return int|string
     */
    public function getChunkNo()
    {
        return $this->chunk_no;
    }

    /**
     * Generated from protobuf field <code>int64 chunk_no = 5 [json_name = "chunkNo"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setChunkNo($var)
    {
        GPBUtil::checkInt64($var);
        $this->chunk_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_size = 6 [json_name = "totalSize"];</code>
     * @return int|string
     */
    public function getTotalSize()
    {
        return $this->total_size;
    }

    /**
     * Generated from protobuf field <code>int64 total_size = 6 [json_name = "totalSize"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 7 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 7 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 8 [json_name = "timestamp"];</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 8 [json_name = "timestamp"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool end_of_stream = 9 [json_name = "endOfStream"];</code>
     * @return bool
     */
    public function getEndOfStream()
    {
        return $this->end_of_stream;
    }

    /**
     * Generated from protobuf field <code>bool end_of_stream = 9 [json_name = "endOfStream"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEndOfStream($var)
    {
        GPBUtil::checkBool($var);
        $this->end_of_stream = $var;

        return $this;
    }

}

