<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mq/v1/mq.proto

namespace Mq\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>mq.v1.SubMessageRequest</code>
 */
class SubMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>int64 batch = 2 [json_name = "batch"];</code>
     */
    protected $batch = 0;
    /**
     * Generated from protobuf field <code>int64 speed_per_sec = 3 [json_name = "speedPerSec"];</code>
     */
    protected $speed_per_sec = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *           wildcard or exact topic
     *     @type int|string $batch
     *     @type int|string $speed_per_sec
     * }
     */
    public function __construct($data = NULL) {
        \Mq\V1\GPBMetadata\Mq::initOnce();
        parent::__construct($data);
    }

    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * wildcard or exact topic
     *
     * Generated from protobuf field <code>string topic = 1 [json_name = "topic"];</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 batch = 2 [json_name = "batch"];</code>
     * @return int|string
     */
    public function getBatch()
    {
        return $this->batch;
    }

    /**
     * Generated from protobuf field <code>int64 batch = 2 [json_name = "batch"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setBatch($var)
    {
        GPBUtil::checkInt64($var);
        $this->batch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 speed_per_sec = 3 [json_name = "speedPerSec"];</code>
     * @return int|string
     */
    public function getSpeedPerSec()
    {
        return $this->speed_per_sec;
    }

    /**
     * Generated from protobuf field <code>int64 speed_per_sec = 3 [json_name = "speedPerSec"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpeedPerSec($var)
    {
        GPBUtil::checkInt64($var);
        $this->speed_per_sec = $var;

        return $this;
    }

}

